spring.datasource.url=jdbc:mysql://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/test?sslMode=VERIFY_IDENTITY
spring.datasource.username=3vR5RLFVSkz6mkW.root
spring.datasource.password=yXRU6Q3hZdbgixuB

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
# spring.datasource.hikari.data-source-properties.trustCertificateKeyStoreUrl=file:src\main\resources\isrgrootx1.pem
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

app.jwt.secret=MC3w7aWpxr5b6yt8fdm66XFvsOIa764FeheJ4CUCgtY
app.jwt.expiration-ms=3600000

spring.datasource.hikari.max-lifetime=300000
spring.datasource.hikari.idle-timeout=240000
spring.datasource.hikari.keepalive-time=120000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.validation-timeout=5000

logging.level.root=INFO
logging.level.com.example.backend=DEBUG
spring.application.name=backend
